- name: "Get the number of processors"
  command: nproc
  register: cpu_count
  changed_when: false

- name: "Disable C-state for all CPUs"
  command: echo "0" > /sys/devices/system/cpu/cpu{{ item }}/cpuidle/state1/disable
  loop: "{{ range(0, cpu_count.stdout | int) | list }}"
  changed_when: false

- name: "Switch CPUs to performance"
  command: "echo performance > /sys/devices/system/cpu/cpu{{ item }}/cpufreq/scaling_governor"
  loop: "{{ range(0, cpu_count.stdout | int) | list }}"
  changed_when: false
