---
# tasks file for disable_cstates
- name: "Check GRUB"
  command: grep '^GRUB_CMDLINE_LINUX_DEFAULT' /etc/default/grub
  register: grub_line
  changed_when: false

- name: "Strip whitespace and newline"
  set_fact:
    grub_line_trimmed: "{{ grub_line.stdout | trim }}"

- block:
    - name: "Disable C-states"
      lineinfile:
        path: "/etc/default/grub"
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_idle.max_cstate=0 processor.max_cstate=0"'

    - name: "Set CPU performance mode"
      lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=enable intel_pstate.max_perf_pct=100 intel_pstate.min_perf_pct=100 cpufreq.default_governor=performance"'

    - name: "Update GRUB configuration"
      command: update-grub
  when:
    - (grub_line_trimmed != 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_idle.max_cstate=0 processor.max_cstate=0"')
    - (grub_line_trimmed != 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=enable intel_pstate.max_perf_pct=100 intel_pstate.min_perf_pct=100 cpufreq.default_governor=performance"')
  notify: Reboot server
