---
# tasks file for disk_mgmt
- name: "Check cryptsetup status"
  command: "lsblk -f"
  register: lsblk_output
  changed_when: false

- block:
    - name: "apt update and install cryptsetup"
      apt:
        update_cache: yes
        name: cryptsetup
        state: present

    - name: "Copy keyfile to target"
      copy:
        src: "{{ src_file }}"
        dest: "{{ dest_file }}"
        mode: "0600"

    - name: "Create LUKS partition using the keyfile"
      command: "cryptsetup luksFormat {{ storage }} --batch-mode --key-file {{ dest_file }}"

    - name: "Open the LUKS-encrypted partition"
      command: cryptsetup luksOpen {{ storage }} encrypted_disk --key-file {{ dest_file }}

    - name: "Create a filesystem"
      filesystem:
        fstype: ext4
        dev: /dev/mapper/encrypted_disk

    - name: "Mount encrypted disk"
      mount:
        path: /mnt/encrypted_disk
        src: /dev/mapper/encrypted_disk
        fstype: ext4
        state: mounted

    - name: "Remove the keyfile"
      ansible.builtin.file:
        path: "{{ dest_file }}"
        state: absent
  when: "'crypto_LUKS' not in lsblk_output.stdout"

- name: "lsblk -f results"
  command: "lsblk -f"
  register: lsblk_results
  changed_when: false

- name: "show lsblk -f results"
  debug:
    msg: "{{ lsblk_results.stdout_lines }}"
